route:
  queue:
    url: https://sqs.eu-central-1.amazonaws.com/423073966355/flight_routes_queue
  providers:
    ase:
      urls: >
        http://ase.asmt.live:8000/provider/flights1,
        http://ase.asmt.live:8000/provider/flights2